version: '3.7'
services:
  db:
    image: postgres:16-alpine
    env_file:
      - ./venv
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    build: .
    command: sh -c 'make migrate && python -m bot'
    env_file:
      - ./venv
    restart: always
    depends_on:
      - db





volumes:
  pgdata: